config/routes.rb
Rails.application.routes.draw do
  root 'news#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :news, only: %i[index] do
    collection do
      get 'search'
      get 'top_news'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  require 'news-api'
  def index
    @data = news_api.get_top_headlines(country: 'us', language: 'en')
  end


  def search
    @data = news_api.get_everything(q: params[:query])
    render :index
  end

  def top_news
    @data = news_api.get_top_headlines(sources: "bbc-news")
    render :index
  end

  private
  def news_api
    @newsapi ||= News.new(ENV.fetch('api_key'))  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "news/navbar" %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/news/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">NEWS APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Country
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/language">India</a></li>
            <li><a class="dropdown-item" href="#">China</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to top_news_news_index_path do %>
            <span class="badge bg-danger">Top News</span>
          <% end %>
        </li>
      </ul>
      <!--- old code 
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->

      <!-- _navbar.html.erb -->

<!-- _navbar.html.erb -->

    <%= form_tag(search_news_index_path, method: :get, class: 'd-flex') do %>
      <%= text_field_tag(:query, params[:query], class: 'form-control me-2', type: 'search', placeholder: 'Search', aria_label: 'Search') %>
      <button class="btn btn-outline-success" type="submit">Search</button>
    <% end %>


    </div>
  </div>
</nav>

app/views/news/_news_card.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @data.each do |res|%>

    <div class="col">
      <div class="card h-100">
        <a href="<%= res.url %>" target="_blank" class="news_card">
          <img src="<%= res.urlToImage ? res.urlToImage : 'https://www.cimspa.co.uk/globalassets/images-cimspa/news-images/_news-placeholder-salmon-navy-1920.png?w=1410' %>" class="card-img-top" alt="image-placeholder">
        </a>
        <div class="card-body">
          <h5 class="card-title"><%= res.title %></h5>
          <p class="card-text"><%= res.description %></p>
        </div>
        <div class="card-footer d-flex justify-content-end">
          <small class="text-body-secondary px-3"><%= time_ago_in_words(res.publishedAt).to_s + ' ago' %></small>
          <span class="badge text-bg-secondary"><%= res.name %></span>
        </div>
      </div>
    </div>

  <% end %>
</div>
<%
=begin%>
 #<Everything:0x00007f9afcdae320
 @author="https://www.facebook.com/peoplemag",
 @content=
  "Taylor Swift and the gang are stepping out!\r\nThe singer, 33, headed out to dinner with Selena Gomez, Sophie Turner, Gigi Hadid, Cara Delevingne and new friend Brittany Mahomes in New York City Saturd… [+3162 chars]",
 @description=
  "Taylor Swift had an evening out with friends including Selena Gomez, Sophie Turner, Brittany Mahomes, Cara Delevingne and Gigi Hadid at Bond St restaurant in New York City on Saturday",
 @id=nil,
 @name="PEOPLE",
 @publishedAt="2023-11-05T18:11:00Z",
 @title="Taylor Swift Has Night Out with Selena Gomez, Sophie Turner, Brittany Mahomes and Gigi Hadid in N.Y.C. - PEOPLE",
 @url="https://people.com/taylor-swift-selena-gomez-sophie-turner-brittany-mahomes-gigi-hadid-8387559",
 @urlToImage=
  "https://people.com/thmb/hP9clncZRCJXz2-SJr0sqRvx4Xg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(708x365:710x367)/Taylor-Swift-Girls-Night-Out-110523-06-8fce9410ecd048e9be177f78fe4ddf26.jpg"> 
<%
=end%>

app/views/news/index.html.erb
<%= render partial: "news_card", :locals => {:data => @data} %>